### ISSUE TITLE
POST sent to prom2teams DOCKER-2.5.6/2.5.7/2.5.8 cannot be parsed - "NameError: name 'EXCLUDE' is not defined"

### ISSUE THREAD

**Issue by gnaex** [idealista/prom2teams#192]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

When an alert is sent to prom2teams it returns a 500 back to alertmanager:
`level=warn ts=2020-07-15T13:09:06.615Z caller=notify.go:674 component=dispatcher receiver=msteams_and_mail_me integration=webhook[0] msg="Notify attempt failed, will retry later" attempts=1 err="unexpected status code 500: http://0.0.0.0:8089/v2/Connector"`

Error seen on docker - sounds similar to error reported before but not same same it seems:
```
2020-07-15 13:09:09,178 - prom2teams_app - ERROR - An unhandled exception occurred. name 'EXCLUDE' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask/views.py", line 87, in view
    self = view.view_class(*class_args, **class_kwargs)
  File "/usr/local/lib/python3.5/site-packages/prom2teams/app/versions/v2/namespace.py", line 18, in __init__
    self.schema = MessageSchema(exclude_fields=app.config['LABELS_EXCLUDED'], exclude_annotations=app.config['ANNOTATIONS_EXCLUDED'], unknown=EXCLUDE)
NameError: name 'EXCLUDE' is not defined
```

### Steps to Reproduce

Forced an error to be sent to prom2teams.

**Expected behavior:** Accepts POST

**Actual behavior:** Fails to parse and returns 500 error as per above

**Reproduces how often:** 100% (each time)

### Versions

The version/s you notice the behavior.

- prom2teams DOCKER image 2.5.6
- prometheus 2.13.1 & alertmanager-0.19.0
   ... as well with updated version that yield the same error
  prometheus 2.19.2 & alertmanager-0.21.0

### Additional Information

Alertmanager config:
```
  webhook_configs:
  - url: "http://0.0.0.0:8089/v2/Connector"
    send_resolved: true
```

Docker image used:
```
$ sudo docker images
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
docker.io/idealista/prom2teams   2.5.6               85a32f6a1d8d        47 hours ago        250 MB
```
How I started docker
`sudo docker run -it -d -e PROM2TEAMS_CONNECTOR=https://outlook.office.com/webhook/xxxxxxx/IncomingWebhook/xxxxxxxxxx -p 8089:8089 idealista/prom2teams:2.5.6`

**Comment by gnaex** [comment]
Tested with docker image 2.5.7 and I still get the same error

```
2020-08-05 12:47:17,103 - flask.app - ERROR - Exception on /v2/Connector [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask/views.py", line 87, in view
    self = view.view_class(*class_args, **class_kwargs)
  File "/usr/local/lib/python3.5/site-packages/prom2teams/app/versions/v2/namespace.py", line 18, in __init__
    self.schema = MessageSchema(exclude_fields=app.config['LABELS_EXCLUDED'], exclude_annotations=app.config['ANNOTATIONS_EXCLUDED'], unknown=EXCLUDE)
TypeError: __init__() got an unexpected keyword argument 'unknown'
2020-08-05 12:47:17,103 - prom2teams_app - ERROR - An unhandled exception occurred. __init__() got an unexpected keyword argument 'unknown'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask/views.py", line 87, in view
    self = view.view_class(*class_args, **class_kwargs)
  File "/usr/local/lib/python3.5/site-packages/prom2teams/app/versions/v2/namespace.py", line 18, in __init__
    self.schema = MessageSchema(exclude_fields=app.config['LABELS_EXCLUDED'], exclude_annotations=app.config['ANNOTATIONS_EXCLUDED'], unknown=EXCLUDE)
TypeError: __init__() got an unexpected keyword argument 'unknown'
2020-08-05 12:47:17,105 - werkzeug - INFO - 172.17.0.1 - - [05/Aug/2020 12:47:17] "POST /v2/Connector HTTP/1.1" 500 -
2020-08-05 12:47:17,112 - werkzeug - ERROR - Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask/views.py", line 87, in view
    self = view.view_class(*class_args, **class_kwargs)
  File "/usr/local/lib/python3.5/site-packages/prom2teams/app/versions/v2/namespace.py", line 18, in __init__
    self.schema = MessageSchema(exclude_fields=app.config['LABELS_EXCLUDED'], exclude_annotations=app.config['ANNOTATIONS_EXCLUDED'], unknown=EXCLUDE)
TypeError: __init__() got an unexpected keyword argument 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/werkzeug/serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/site-packages/werkzeug/serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1748, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
  File "/usr/local/lib/python3.5/site-packages/prom2teams/app/api.py", line 26, in error_handler
    return str(e), e.code
AttributeError: 'TypeError' object has no attribute 'code'
```

**Comment by gnaex** [comment]
Tested with latest 2.5.8 and it still fails and the docker cannot be used at all.

2020-09-03 08:14:15,111 - flask.app - ERROR - Exception on /v2/Connector [POST]
```
..
  File "/usr/local/lib/python3.5/site-packages/prom2teams/app/versions/v2/namespace.py", line 18, in __init__
    self.schema = MessageSchema(exclude_fields=app.config['LABELS_EXCLUDED'], exclude_annotations=app.config['ANNOTATIONS_EXCLUDED'], unknown=EXCLUDE)
TypeError: __init__() got an unexpected keyword argument 'unknown'
...
  File "/usr/local/lib/python3.5/site-packages/flask/views.py", line 87, in view
    self = view.view_class(*class_args, **class_kwargs)
  File "/usr/local/lib/python3.5/site-packages/prom2teams/app/versions/v2/namespace.py", line 18, in __init__
    self.schema = MessageSchema(exclude_fields=app.config['LABELS_EXCLUDED'], exclude_annotations=app.config['ANNOTATIONS_EXCLUDED'], unknown=EXCLUDE)
TypeError: __init__() got an unexpected keyword argument 'unknown'
2020-09-03 08:14:15,114 - werkzeug - INFO - 172.17.0.1 - - [03/Sep/2020 08:14:15] "POST /v2/Connector HTTP/1.1" 500 -

```

**Comment by gnaex** [comment]
Tested and works with 2.6.0. Can be closed!
